### ISSUE TITLE
Compatibility with Elasticsearch Domain hidden behind a Loadbalancer

### ISSUE THREAD

**Issue by apaz037** [github/vulcanizer#32]
Issue: When trying to access an Elasticsearch Domain behind a loadbalancer, a port is being forcibly attached to the request.

```bash
❯ vulcanizer settings -c prod
Error getting settings: dial tcp 0.0.0.0:0: connect: can't assign requested address
Get http://elasticsearchdomain.es.amazonaws.com:0/_cluster/settings: dial tcp 0.0.0.0:0: connect: can't assign requested address
```

Proposed Solution: If no port is specified in the .vulcanizer.yaml, no port should be attached to the request URL.

**Comment by nickcanz** [comment]
Hey @apaz037 thanks for this issue! Your proposed solution seems like a good plan, I'll take a look at it tonight or tomorrow.

**Comment by apaz037** [comment]
Awesome, Thanks! I think I've got a working PR ready to submit if you're available to review! =]

**Comment by nickcanz** [comment]
Sure, would be happy to review a PR!

**Comment by apaz037** [comment]
PR #33 submitted.

**Comment by nickcanz** [comment]
Thanks for the fix @apaz037!

**Comment by apaz037** [comment]
Np! I actually just tested it and there are calls that are not going through that method to generate the URL.

I've found the location it is actually doing it at and will be submitting a fix for the functionality now.
I've tested the fix and it is working properly.  reopening this issue and resubmitting PR.

**Comment by apaz037** [comment]
#34 has been created to fix this issue.

Sorry for not testing 100% originally!

**Comment by nickcanz** [comment]
👍
