### ISSUE TITLE
Snapshot list show incorrect finished date while running a snapshot

### ISSUE THREAD

**Issue by marctc** [github/vulcanizer#35]
I've been trying the snapshot functionallity of vulcanizer but when I run `list` command while a snapshot process is running the `FINISHED` and `DURATION` columns show this information:
```
$ vulcanizer snapshot -c c0 list -r r0
+-------------+-----------+----------------------+-------------------+
|    STATE    |   NAME    |       FINISHED       |     DURATION      |
+-------------+-----------+----------------------+-------------------+
| IN_PROGRESS | test      | 1970-01-01T00:00:00Z | -431225h3m27.241s |
+-------------+-----------+----------------------+-------------------+
```

If I curl the `_snapshot` endpoint of the Elasticsearch cluster I can see that `end_time` is actually wrong:
```
$ curl -X GET "localhost:9200/_snapshot/r0/_current" | jq .  
{
  "snapshots": [
    {
      "snapshot": "test",
      "uuid": "f3jm-sDnTHqmLrEq-JLEpw",
      "version_id": 5061099,
      "version": "5.6.10",
      "indices": [
        ".ltrstore",
        "live",
        "settings"
      ],
      "state": "IN_PROGRESS",
      "start_time": "2019-03-12T17:03:27.241Z",
      "start_time_in_millis": 1552410207241,
      "end_time": "1970-01-01T00:00:00.000Z",
      "end_time_in_millis": 0,
      "duration_in_millis": -1552410207241,
      "failures": [],
      "shards": {
        "total": 0,
        "failed": 0,
        "successful": 0
      }
    }
  ]
}

```
Once the snapshot finished, the `FINISHED` and `DURATION` columns show a correct result.

If this is an issue of ES, should vulcanizer check this before showing weird results?

**Comment by nickcanz** [comment]
Thanks for the issue @marctc! While this is from Elasticsearch itself, I agree that we can try to be a little smarter and detect this case.

**Comment by marctc** [comment]
I can try to fix it you want @nickcanz

**Comment by nickcanz** [comment]
@marctc it'd be great for you to contribute that fix if you want to!

**Comment by nickcanz** [comment]
Closed in https://github.com/github/vulcanizer/pull/48
