### ISSUE TITLE
Add an ability to set multiple hosts per cluster

### ISSUE THREAD

**Issue by Oloremo** [github/vulcanizer#53]
Hi!

As I understand right now it's possible to pass only a single host per cluster which is not very convenient since ES could easily survive a failer of a single node and continue to work.

I'd like to pass a list of hosts and make vulcanizer try to connect to them all in some kind of order with some kind of timeouts.

Does it make sense?

**Comment by nickcanz** [comment]
Hi @Oloremo,

Your request does make sense, but at this time I'm wary of complicating the connection logic with retrying/round-robining requests. 

For now, my expectation is that people using vulcanizer for a large cluster would point to some kind of load balancer and/or perhaps use some kind of existing service discovery to pass the host/port to vulcanizer. 

Thank you for the request! But it's a little too complicated at this stage of the project.
