### ISSUE TITLE
Passing authentication through Go API

### ISSUE THREAD

**Issue by harrisonlob** [github/vulcanizer#61]
Am I understanding your library correctly that currently there is no way to create a new client to interact with elasticsearch by just passing in the elasticsearch username, host, port and password to create a connection with a certain elasticsearch host? 

I have credentials that I'd much rather just pass into a function to create a client rather than writing to a file like `~/.vulcanizer.yaml` and then calling `NewClient()` on after writing to that file. Thanks

**Comment by nickcanz** [comment]
Hi @harrisonlob,

If you're just programming in Go and not using the `vulcanizer` CLI library, then you do not need the file-based configuration.

You can set up your client and then modify the struct values like in: https://github.com/github/vulcanizer/blob/2c833b0a003e1b57162ede328e2bcc150ce12b88/cmd/vulcanizer/main.go#L68

Full client settings can be seen here: https://godoc.org/github.com/github/vulcanizer#Client

Feel free to re-open if this doesn't help!

**Comment by harrisonlob** [comment]
@nickcanz ah yes, duh of course! Really appreciate the quick response.
