### ISSUE TITLE
Get index settings for "private" indices not working

### ISSUE THREAD

**Issue by hhprogram** [github/vulcanizer#62]
**Note:** when I say "private" I mean elasticsearch indices beginning with a `.` (i.e `.security-*` indices or `.watches` index etc..) couldn't find the official term.

Use case is if I want to check the index settings for a `.security` index (assume this exists in the cluster). Right now if I pass in `.security` into the [GetIndexSettings function](https://github.com/github/vulcanizer/blob/master/es.go#L1008), the underlying function call `handleErrWithBytes` correctly retrieves the necessary info - however when calling [get bytes](https://godoc.org/github.com/tidwall/gjson#GetBytes), it will 'fail' and return an empty [Result object](https://godoc.org/github.com/tidwall/gjson#Result) 

I think this is because the [underlying Get function](https://github.com/tidwall/gjson/blob/dc5b8eacf499360f037a149e5cdf4e15ee73d1f0/gjson.go#L1425) requires input strings to escape `.` characters but the `handleErrWithBytes` just takes the value as is. Thus, if I pass in a string with an escaped `.` then the `handleErrWithBytes` will return an empty body but if assuming I somehow got the body JSON response back - then the [underlying Get function](https://github.com/tidwall/gjson/blob/dc5b8eacf499360f037a149e5cdf4e15ee73d1f0/gjson.go#L1425) would have properly retrieved the string because I escaped the `.` and it would know how to interpret that `path`.

I have a current workaround which is just to pass in `*security` into the `GetIndexSettings` function - but I feel like the ideal would not have to do that. Let me know if you'd like some example code or need anymore clarification.

**Comment by nickcanz** [comment]
Hi @hhprogram 

Sorry for the delay! I've created a branch that should fix this: https://github.com/github/vulcanizer/pull/63

**Comment by nickcanz** [comment]
I've released v0.5.1 for this bug fix: https://github.com/github/vulcanizer/releases/tag/v0.5.1

**Comment by hhprogram** [comment]
No worries! Thanks for merging in the bug fix!
