### ISSUE TITLE
Allow setting cluster settings to null

### ISSUE THREAD

**Issue by leosunmo** [github/vulcanizer#68]
First of all, thanks a ton for this library, makes my life so much easier managing Elasticsearch!!

My usecase for this is the following. I defer a `RestoreClusterSettings()` function so that I can reset whatever settings I've made changes to during operation after I'm done, or I cancel.
The `originalValue, newValue := SetClusterSetting(...)` pattern makes this really easy, _however_, if this setting was unset previously the `originalValue` is an empty string.

This leads to the following error when I restore cluster settings:
```
failed to restore cluster setting indices.recovery.max_bytes_per_sec: Bad HTTP Status from Elasticsearch: 400, {"error":{"root_cause":[{"type":"remote_transport_exception","reason":"[mynode][10.1337.1.1:9300][cluster:admin/settings/update]"}],"type":"illegal_argument_exception","reason":"failed to parse setting [indices.recovery.max_bytes_per_sec] with value [] as a size in bytes: unit is missing or unrecognized","caused_by":{"type":"parse_exception","reason":"failed to parse setting [indices.recovery.max_bytes_per_sec] with value [] as a size in bytes: unit is missing or unrecognized"}},"status":400}
```

It would be nice if either `SetClusterSetting` could handle this, or if we created a new function to set a setting to Null in Elasticsearch (to fall back to the default value).

I tried passing in the string "null" as well, but it expects an actual JSON null value rather than a string "null".

Resetting a value in 7.5: https://www.elastic.co/guide/en/elasticsearch/reference/7.5/cluster-update-settings.html
This procedure is the same in 5.x as well, so shouldn't be a breaking change: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/cluster-update-settings.html

**Comment by nickcanz** [comment]
Thanks for this issue @leosunmo! Totally agree we should handle this.

I'm debating right now between three options:

1. adding a new `ClearClusterSetting(string)` function 
1. changing the signature of `SetClusterSetting(string, string)`  to `SetClusterSetting(string, *string)` so you can actually pass `nil` to the function
1. add a special case for when `"null"` is passed to `SetClusterSetting`. 

Right now I'm leaning towards option 3, although it's a little messy code-wise, that's the thing I would have tried intuitively as well.

**Comment by leosunmo** [comment]
Hey @nickcanz , thanks for your reply.

Since the user is supposed to save the original setting and perform actions based on it (like resetting the settings once their operation is complete) we have to keep that in mind.

1. This could be an OK setup, just have to keep in mind that the user is supposed to use the return of `SetClusterSetting()`. Here's probably how I would use it:
```go
oldSetting, newSetting, err := client.SetClusterSetting(setting, value)
defer func() {
  if oldSetting == "" {
      ClearClusterSetting(setting)
      return
  }
  client.SetClusterSetting(setting, oldSetting)
}()
```

2. If you change the signature to use pointers you'll probably have to change the return as well (so it can be used when resetting the settings using the `oldSetting` return). Documentation around the function also has to be very clear.
```go
oldSetting, newSetting, err := client.SetClusterSetting(setting, valuePtr)
defer func() {
  client.SetClusterSetting(setting, oldSetting) // oldSetting has to be a pointer as well or we'll have to check if it's nil all the time.
}()
```

3. This is a bit messy and confusing since the `"null"` is a string, not an actual [JSON `null` value](https://tools.ietf.org/html/rfc8259#section-3), which is not a string. 
`SetClusterSetting()` would also have to check if the return from Elasticsearch is `""`/`null` and return a `"null"` string instead, otherwise it couldn't be used in a `defer` like I did above.
If `SetClusterSetting()` returned a `"null"` string it _would_ be quite tidy from a code perspective.
```go
oldSetting, newSetting, err := client.SetClusterSetting(setting, value)
defer func() {
  client.SetClusterSetting(setting, oldSetting) // We don't care if oldSetting is "500" or unset/"null" because SetClusterSetting will deal with it internally.
}()
```
If the user wants to use the value for something other than `SetClusterSetting()` it might a bit confusing when the value is suddenly a `"null"` string however, so documentation will be important.

**Comment by leosunmo** [comment]
I'm not quite sure which one I prefer yet. I guess if I was writing `SetClusterSetting` from scratch I'd probably use string pointers since it makes sense when you marshal the response from ES you'd get nil values where the value wasn't explicitly set.

**Comment by leosunmo** [comment]
If you could have a think after the holidays I could send a PR implementing a solution.

**Comment by nickcanz** [comment]
Hey @leosunmo! 

I would gladly accept a PR to change the signature to use string pointers, thanks for your thoughts on this.

**Comment by leosunmo** [comment]
Will work on this when I get time
