### ISSUE TITLE
Get Disk Allocation information for Nodes

### ISSUE THREAD

**Issue by leosunmo** [github/vulcanizer#70]
I have a need to get disk allocation/usage information from the `_cat/allocation` API. Ideally it would combine with the information from `_cat/nodes`/`GetNodes()`.

I have a working PR at https://github.com/github/vulcanizer/pull/69 that implements this by adding the disk allocation information to the existing Node struct. It should probably be a flag or subcommand in the CLI for `vulcanizer nodes`. Flag would probably be tidier.

**Comment by leosunmo** [comment]
Here's an example from an internal Slack Bot using my fork of Vulcanzier with Pr #69 implemented.
![image](https://user-images.githubusercontent.com/13341934/71567707-f1477d80-2b25-11ea-8f80-b461e33c5780.png)

**Comment by nickcanz** [comment]
Closed by #69
