### ISSUE TITLE
Release v0.5.2

### ISSUE THREAD

**Issue by leosunmo** [github/vulcanizer#80]
There's quite a few changes since 0.5.1 and it would be nice to have a new release and not have to use forks or specific commits!

While running my own version `v0.5.2` in a fork, I discovered an issue in the new release (`v0.2.16`)  of `gorequest`.

There's been some changes to how it detects `content-type` which breaks Vulcanizer when talking to Elasticsearch 1.7. So be careful when you upgrade dependencies!
If you _do_ want to upgrade `gorequest`, you will need to explicitly set the `content-type` in https://github.com/github/vulcanizer/blob/dc3a2fd9fe0e6b9c9505eea33807c5f47a1fbc87/es.go#L352 by changing that line to:
```
agent := gorequest.New().Set("Accept", "application/json").Set("content-type","application/json")
```
This change works with ES 1.7, ES 5.6, and ES 7.7.

**Comment by nickcanz** [comment]
Whew, a release is really overdue, thank you @leosunmo! 

I've cut v0.6.0 https://github.com/github/vulcanizer/releases/tag/v0.6.0

**Comment by nickcanz** [comment]
I've incorporated the Content-Type addition as well! Thanks for that warning!

**Comment by leosunmo** [comment]
Thanks a ton Nick! That content-type thing took me _so long_ to figure out.
