### ISSUE TITLE
A link in this repo's readme points to a folder called "vendor" which does not (or no longer?) exists in this repo. Gives Status code [404:NotFound]

### ISSUE THREAD

**Issue by MrCull** [github/vulcanizer#84]
The link in this repo's readme is:
Status code [404:NotFound] - Link: https://github.com/github/vulcanizer/tree/master/vendor

This is near the bottom in the License section.

However there is not file/folder in this repo (any more?) with this name.

## Extra 

This bad link was found using a tool I recently created that uses the GitHub API to find repos and then validate the links within the readme file:
https://github.com/MrCull/GitHub-Repo-ReadMe-Dead-Link-Finder

It can be used to re-check this repo via: http://githubreadmechecker.com/Home/Search?SingleRepoUri=https%3a%2f%2fgithub.com%2fgithub%2fvulcanizer

I'd love to head some feedback on this project/tool.
So please feel free to share any thoughts or comments.

**Comment by nickcanz** [comment]
Fixed in https://github.com/github/vulcanizer/commit/ea4ed1266980d04cf099ac741368cbccecf9d168
