### ISSUE TITLE
Provide pre built releases for the major platforms

### ISSUE THREAD

**Issue by breml** [github/vulcanizer#85]
It would be very convenient if this project could provide pre built releases for the major platforms e.g. via [GoReleaser](https://goreleaser.com/). Installing it via `go get -u` or `git clone` and then use the custom build script is not optimal.

**Comment by nickcanz** [comment]
You're right, this makes sense. I'll take a look at how to implement it!

**Comment by nickcanz** [comment]
Hi @breml, thanks for the suggestion! Added it in a PR here: https://github.com/github/vulcanizer/pull/86

And an example of what a release looks like: https://github.com/github/vulcanizer/releases/tag/v0.6.2

**Comment by breml** [comment]
@nickcanz Great, thanks.
